### ISSUE TITLE
Requiring node modules

### ISSUE THREAD

**Issue by rohit8** [ddliu/motto#1]
I am trying to render reactjs on the server using otto. My entry point is called `app.js` and requires modules installed through npm, who also have dependencies in node_modules. Is there a straight forward way to run `app.js` in motto with all of its node dependencies?

**Comment by ddliu** [comment]
Assume that your project structure is like this:

```
prj/
    app.js
    node_modules/
        mod_a/
        mod_b/
    package.json
```

After installing `motto`:

```
go install github.com/ddliu/motto/motto
```

Just run your entry file:

```
motto path/to/prj/app.js
```
